namespace McToTm.Core;

public static class BlockMapping
{
    private static readonly Dictionary<string, byte> TmBlockEnum = new(StringComparer.OrdinalIgnoreCase)
    {
        ["none"] = 0, ["grass"] = 1, ["dirt"] = 2, ["sand"] = 3, ["scoria"] = 4,
        ["wood"] = 5, ["woodplank"] = 6, ["woodveneer"] = 7, ["leaves"] = 8, ["glass"] = 9,
        ["cloud"] = 10, ["water"] = 11, ["copper"] = 12, ["lava"] = 13, ["cassiterite"] = 14,
        ["clay"] = 15, ["sandstone"] = 16, ["limestone"] = 17, ["basalt"] = 18, ["andesite"] = 19,
        ["dacite"] = 20, ["diorite"] = 21, ["tuff"] = 22, ["serpentine"] = 23, ["gabbro"] = 24,
        ["granite"] = 25, ["komatiite"] = 26, ["marble"] = 27, ["rhyolite"] = 28, ["bedrock"] = 29,
        ["carbon"] = 30, ["obsidian"] = 31, ["coal"] = 32, ["flint"] = 33, ["greenstone"] = 34,
        ["diamond"] = 35, ["ruby"] = 36, ["gold"] = 37, ["platinum"] = 38, ["iron"] = 39,
        ["opal"] = 40, ["uranium"] = 41, ["cobblestone"] = 42, ["bricks"] = 43, ["chess"] = 44,
        ["bookcase"] = 45, ["torch"] = 46, ["ladder"] = 47, ["workbench"] = 48, ["furnace"] = 49,
        ["chest"] = 50, ["wooddoortop"] = 51, ["steeldoortop"] = 52, ["teleport"] = 53,
        ["tnt"] = 54, ["c4"] = 55, ["wisdom"] = 56, ["blueprint"] = 57, ["sapling"] = 58,
        ["whiteflowers"] = 59, ["purpleflowers"] = 60, ["redflowers"] = 61, ["yellowflowers"] = 62,
        ["pineleaves"] = 63, ["itemshop"] = 64, ["blockshop"] = 65, ["sulphur"] = 66,
        ["cyclonite"] = 67, ["titanium"] = 68, ["teflon"] = 69, ["fluorite"] = 70,
        ["wovenleaves"] = 71, ["rope"] = 72, ["multitextureblock"] = 73,
        ["mossycobblestone"] = 74, ["pane"] = 75, ["stainedglasspane"] = 76, ["post"] = 77,
        ["healthblock"] = 78, ["grassystone"] = 79, ["bluebox"] = 80,
        ["customblock1"] = 81, ["customblock2"] = 82, ["customblock3"] = 83,
        ["customblock4"] = 84, ["customblock5"] = 85, ["customblock6"] = 86,
        ["customblock7"] = 87, ["customblock8"] = 88, ["customblock9"] = 89,
        ["customblock10"] = 90,
        ["userdefined1"] = 91, ["userdefined2"] = 92, ["userdefined3"] = 93,
        ["userdefined4"] = 94, ["userdefined5"] = 95, ["userdefined6"] = 96,
        ["userdefined7"] = 97, ["userdefined8"] = 98, ["userdefined9"] = 99,
        ["voidmarker"] = 100, ["rasta"] = 101, ["whitetile"] = 102, ["checkered"] = 103,
        ["retro"] = 104, ["cherrymetal"] = 105, ["static"] = 106, ["ice"] = 107,
        ["concretebrick"] = 108, ["turkish"] = 109, ["camouflage"] = 110,
        ["spideregg"] = 111, ["longgrass"] = 112, ["stairs"] = 113,
        ["ambientsoundblock"] = 114, ["wooddoorbottom"] = 115, ["steeldoorbottom"] = 116,
        ["sign"] = 117, ["fire"] = 118, ["steelspikes"] = 119, ["climbingivy"] = 120,
        ["book"] = 121, ["key"] = 122, ["rareschest"] = 123, ["crop"] = 124,
        ["invisiblebarrier"] = 125, ["coverblock"] = 126, ["redmushroom"] = 127,
        ["arcademachine"] = 128, ["particleemitter"] = 129, ["stack"] = 130,
        ["upsidedownstack"] = 131, ["lockedchest"] = 132, ["litfurnace"] = 133,
        ["whitewool"] = 134, ["bedhead"] = 135, ["bedfoot"] = 136, ["npcspawn"] = 137,
        ["crate"] = 138, ["fence"] = 139, ["lockeddoortop"] = 140, ["sunbox"] = 141,
        ["sentryturret"] = 142, ["proximitydetector"] = 143, ["snow"] = 144,
        ["snowlayer"] = 145, ["scaffold"] = 146, ["steelportcullis"] = 147,
        ["steelplating"] = 148, ["halfblock"] = 149, ["ramp"] = 150, ["cactus"] = 151,
        ["terracottatile"] = 152, ["onewayglass"] = 153, ["cylinder"] = 154,
        ["goldblock"] = 155, ["stonewall"] = 156, ["sandbrick"] = 157, ["table"] = 158,
        ["gildedwoodpanel"] = 159, ["painting"] = 160, ["grassshaded"] = 161,
        ["mapleleaves"] = 162, ["wifitransmitter"] = 163, ["wifireceiver"] = 164,
        ["pressureplate"] = 165, ["poweredlight"] = 166, ["safe"] = 167, ["sundial"] = 168,
        ["switch"] = 169, ["button"] = 170, ["trapdoor"] = 171, ["scriptblock"] = 172,
        ["tilledearth"] = 173, ["saltblock"] = 174, ["entityspawn"] = 175, ["bone"] = 176,
        ["sapphire"] = 177, ["stonebrick"] = 178, ["birchwood"] = 179,
        ["birchwoodplank"] = 180, ["stainedglass"] = 181,
        ["polishedbasalt"] = 192, ["polishedandesite"] = 193, ["polisheddacite"] = 194,
        ["polisheddiorite"] = 195, ["polishedtuff"] = 196, ["polishedserpentine"] = 197,
        ["polishedgabbro"] = 198, ["polishedgranite"] = 199, ["polishedkomatiite"] = 200,
        ["polishedmarble"] = 201, ["polishedrhyolite"] = 202, ["polishedgreenstone"] = 203,
        ["lockeddoorbottom"] = 204,
        ["polishedbasaltbrick"] = 205, ["polishedandesitebrick"] = 206,
        ["polisheddacitebrick"] = 207, ["polisheddioritebrick"] = 208,
        ["polishedtuffbrick"] = 209, ["polishedserpentinebrick"] = 210,
        ["polishedgabbrobrick"] = 211, ["polishedgranitebrick"] = 212,
        ["polishedkomatiitebrick"] = 213, ["polishedmarblebrick"] = 214,
        ["polishedrhyolitebrick"] = 215, ["polishedgreenstonebrick"] = 216,
        ["console"] = 217, ["techpanel"] = 218, ["techlamp"] = 219, ["techfurnace"] = 220,
        ["plasmaconduit"] = 221, ["steelvent"] = 222, ["berrybush"] = 223,
        ["colorsmoothgray"] = 224, ["colorbloodOrange"] = 225, ["colorlime"] = 226,
        ["colorlighttan"] = 227, ["colorleather"] = 228, ["colorlightorange"] = 229,
        ["colorlightyellow"] = 230, ["colorlightblue"] = 231, ["colordarkblue"] = 232,
        ["colorlightgreen"] = 233, ["colordarkbrown"] = 234, ["colortan"] = 235,
        ["colorcreme"] = 236, ["colordarkred"] = 237, ["colordarkgray"] = 238,
        ["colorgray"] = 239, ["colordarkgreen"] = 240, ["colorpink"] = 241,
        ["colorpurple"] = 242, ["colorcyan"] = 243, ["colorblack"] = 244,
        ["colorwhite"] = 245, ["coloryellow"] = 246, ["colorred"] = 247,
        ["colororange"] = 248, ["colorlightbrown"] = 249, ["colorbrown"] = 250,
        ["colorgreen"] = 251, ["colorblue"] = 252,
        ["marker"] = 253, ["excludemarker"] = 254,
    };

    private static readonly HashSet<string> SkipBlocks = new(StringComparer.OrdinalIgnoreCase)
    {
        "air", "cave_air", "void_air", "barrier", "structure_void", "light",
        "moving_piston", "piston_head", "fire", "soul_fire", "lava", "flowing_lava",
        "end_portal", "end_gateway", "nether_portal",
        "carrots", "potatoes", "beetroots", "sweet_berry_bush",
        "cave_vines", "cave_vines_plant", "kelp", "kelp_plant",
        "seagrass", "tall_seagrass", "sea_pickle", "turtle_egg",
        "redstone_wire", "repeater", "comparator", "tripwire", "tripwire_hook", "string",
        "rail", "powered_rail", "detector_rail", "activator_rail",
        "piglin_head", "player_head", "skeleton_skull", "wither_skeleton_skull",
        "zombie_head", "creeper_head", "dragon_head",
        "candle", "white_candle", "orange_candle", "magenta_candle",
        "light_blue_candle", "yellow_candle", "lime_candle", "pink_candle",
        "gray_candle", "light_gray_candle", "cyan_candle", "purple_candle",
        "blue_candle", "brown_candle", "green_candle", "red_candle", "black_candle",
        "wheat",
    };

    private static readonly Dictionary<string, string> DoorBlocks = new(StringComparer.OrdinalIgnoreCase)
    {
        ["iron_door"] = "steeldoortop", ["oak_door"] = "wooddoortop",
        ["spruce_door"] = "wooddoortop", ["birch_door"] = "wooddoortop",
        ["jungle_door"] = "wooddoortop", ["acacia_door"] = "wooddoortop",
        ["dark_oak_door"] = "wooddoortop", ["mangrove_door"] = "wooddoortop",
        ["cherry_door"] = "wooddoortop", ["bamboo_door"] = "wooddoortop",
        ["crimson_door"] = "wooddoortop", ["warped_door"] = "wooddoortop",
        ["copper_door"] = "steeldoortop", ["exposed_copper_door"] = "steeldoortop",
        ["weathered_copper_door"] = "steeldoortop", ["oxidized_copper_door"] = "steeldoortop",
        ["waxed_copper_door"] = "steeldoortop", ["waxed_exposed_copper_door"] = "steeldoortop",
        ["waxed_weathered_copper_door"] = "steeldoortop", ["waxed_oxidized_copper_door"] = "steeldoortop",
        ["pale_oak_door"] = "wooddoortop",
    };

    private static readonly Dictionary<string, string?> McToTm = new(StringComparer.OrdinalIgnoreCase)
    {
        ["andesite"] = "limestone", ["stone"] = "granite",
        ["cracked_stone_bricks"] = "polisheddacitebrick",
        ["grass_block"] = "grass", ["grass_path"] = "dirt", ["dirt_path"] = "dirt",
        ["planks"] = "woodplank", ["log"] = "wood", ["log2"] = "wood",
        ["leaves"] = "leaves", ["leaves2"] = "leaves",
        ["wool"] = "whitewool", ["stained_glass"] = "stainedglass",
        ["stained_glass_pane"] = "stainedglass",
        ["double_stone_slab"] = "halfblock", ["stone_slab"] = "halfblock",
        ["wooden_slab"] = "halfblock", ["double_wooden_slab"] = "halfblock",
        ["gravel"] = "diorite", ["stone_bricks"] = "stonebrick",
        ["stone_brick_stairs"] = "stairs", ["cobblestone_stairs"] = "stairs",
        ["oak_stairs"] = "stairs", ["spruce_stairs"] = "stairs",
        ["birch_stairs"] = "stairs", ["jungle_stairs"] = "stairs",
        ["acacia_stairs"] = "stairs", ["dark_oak_stairs"] = "stairs",
        ["brick_stairs"] = "stairs", ["sandstone_stairs"] = "stairs",
        ["red_sandstone_stairs"] = "stairs", ["quartz_stairs"] = "stairs",
        ["nether_brick_stairs"] = "stairs", ["purpur_stairs"] = "stairs",
        ["stone_stairs"] = "stairs", ["smooth_quartz_stairs"] = "stairs",
        ["andesite_stairs"] = "stairs", ["diorite_stairs"] = "stairs",
        ["granite_stairs"] = "stairs", ["tuff_stairs"] = "stairs",
        ["smooth_quartz"] = "polishedmarble", ["smooth_quartz_slab"] = "halfblock",
        ["quartz_bricks"] = "polishedmarble", ["quartz_pillar"] = "polishedmarble",
        ["quartz_block"] = "polishedmarble", ["chiseled_quartz_block"] = "polishedmarble",
        ["smooth_stone_slab"] = "halfblock", ["andesite_slab"] = "halfblock",
        ["diorite_slab"] = "halfblock", ["granite_slab"] = "halfblock",
        ["tuff_slab"] = "halfblock", ["cobblestone_slab"] = "halfblock",
        ["brick_slab"] = "halfblock", ["sandstone_slab"] = "halfblock",
        ["quartz_slab"] = "halfblock", ["oak_slab"] = "halfblock",
        ["spruce_slab"] = "halfblock", ["birch_slab"] = "halfblock",
        ["jungle_slab"] = "halfblock", ["acacia_slab"] = "halfblock",
        ["dark_oak_slab"] = "halfblock", ["nether_brick_slab"] = "halfblock",
        ["red_sandstone_slab"] = "halfblock", ["purpur_slab"] = "halfblock",
        ["cobblestone_wall"] = "cobblestone", ["mossy_cobblestone_wall"] = "mossycobblestone",
        ["stone_brick_wall"] = "stonebrick", ["andesite_wall"] = "stonebrick",
        ["diorite_wall"] = "colorsmoothgray", ["granite_wall"] = "iron",
        ["brick_wall"] = "bricks", ["sandstone_wall"] = "sandstone",
        ["nether_brick_wall"] = "bricks", ["tuff_wall"] = "stonebrick",
        ["fence"] = "fence", ["spruce_fence"] = "fence", ["birch_fence"] = "fence",
        ["jungle_fence"] = "fence", ["dark_oak_fence"] = "fence", ["acacia_fence"] = "fence",
        ["fence_gate"] = "fence", ["spruce_fence_gate"] = "fence",
        ["birch_fence_gate"] = "fence", ["jungle_fence_gate"] = "fence",
        ["dark_oak_fence_gate"] = "fence", ["acacia_fence_gate"] = "fence",
        ["oak_fence"] = "fence", ["oak_fence_gate"] = "fence",
        ["nether_brick_fence"] = "fence", ["iron_bars"] = "steelportcullis",
        ["glass_pane"] = "glass",
        ["hardened_clay"] = "stonebrick", ["stained_clay"] = "stonebrick",
        ["monster_egg"] = "stonebrick", ["hay_block"] = "goldblock",
        ["coal_block"] = "coal", ["packed_ice"] = "ice",
        ["sea_lantern"] = "techlamp", ["glowstone"] = "techlamp",
        ["redstone_lamp"] = "techlamp", ["lit_redstone_lamp"] = "techlamp",
        ["netherrack"] = "bricks", ["soul_sand"] = "sand",
        ["nether_bricks"] = "bricks", ["red_nether_bricks"] = "bricks",
        ["end_stone"] = "sandstone", ["end_stone_bricks"] = "sandstone",
        ["purpur_block"] = "polishedmarble", ["purpur_pillar"] = "polishedmarble",
        ["prismarine"] = "colorsmoothgray", ["prismarine_bricks"] = "colorsmoothgray",
        ["dark_prismarine"] = "colordarkgreen", ["bone_block"] = "bone",
        ["magma_block"] = "colordarkred", ["nether_wart_block"] = "colordarkred",
        ["spawner"] = "steelportcullis",
        ["chest"] = "chest", ["trapped_chest"] = "chest", ["ender_chest"] = "chest",
        ["shulker_box"] = "chest",
        ["white_shulker_box"] = "chest", ["orange_shulker_box"] = "chest",
        ["magenta_shulker_box"] = "chest", ["light_blue_shulker_box"] = "chest",
        ["yellow_shulker_box"] = "chest", ["lime_shulker_box"] = "chest",
        ["pink_shulker_box"] = "chest", ["gray_shulker_box"] = "chest",
        ["light_gray_shulker_box"] = "chest", ["cyan_shulker_box"] = "chest",
        ["purple_shulker_box"] = "chest", ["blue_shulker_box"] = "chest",
        ["brown_shulker_box"] = "chest", ["green_shulker_box"] = "chest",
        ["red_shulker_box"] = "chest", ["black_shulker_box"] = "chest",
        ["crafting_table"] = "table", ["furnace"] = "stonebrick",
        ["lit_furnace"] = "stonebrick", ["anvil"] = "steelplating",
        ["cauldron"] = "cylinder", ["water_cauldron"] = "cylinder",
        ["lava_cauldron"] = "cylinder", ["powder_snow_cauldron"] = "cylinder",
        ["hopper"] = "steelplating", ["beacon"] = "glass",
        ["enchanting_table"] = "table", ["brewing_stand"] = "entityspawn",
        ["bookshelf"] = "bookcase", ["jukebox"] = "woodplank", ["noteblock"] = "woodplank",
        ["note_block"] = "woodplank",
        ["torch"] = "torch", ["wall_torch"] = "torch",
        ["soul_torch"] = "torch", ["soul_wall_torch"] = "torch",
        ["redstone_torch"] = "torch", ["redstone_wall_torch"] = "torch",
        ["lantern"] = "torch", ["soul_lantern"] = "techlamp",
        ["campfire"] = "poweredlight", ["soul_campfire"] = "poweredlight",
        ["flower_pot"] = "bricks", ["emerald_block"] = "fluorite",
        ["emerald_ore"] = "uranium", ["farmland"] = "tilledearth",
        ["glow_lichen"] = "climbingivy",
        ["oak_trapdoor"] = "trapdoor", ["spruce_trapdoor"] = "trapdoor",
        ["birch_trapdoor"] = "trapdoor", ["jungle_trapdoor"] = "trapdoor",
        ["acacia_trapdoor"] = "trapdoor", ["dark_oak_trapdoor"] = "trapdoor",
        ["iron_trapdoor"] = "trapdoor", ["ladder"] = "woodplank",
        ["vine"] = "climbingivy", ["lily_pad"] = "leaves", ["sugar_cane"] = "leaves",
        ["cobweb"] = "colorwhite", ["dead_bush"] = "longgrass",
        ["tall_grass"] = "longgrass", ["short_grass"] = "longgrass",
        ["large_fern"] = "longgrass", ["fern"] = "longgrass",
        ["sunflower"] = "yellowflowers", ["lilac"] = "purpleflowers",
        ["rose_bush"] = "redflowers", ["peony"] = "whiteflowers",
        ["dandelion"] = "yellowflowers", ["poppy"] = "redflowers",
        ["blue_orchid"] = "purpleflowers", ["allium"] = "purpleflowers",
        ["azure_bluet"] = "whiteflowers", ["red_tulip"] = "redflowers",
        ["orange_tulip"] = "yellowflowers", ["white_tulip"] = "whiteflowers",
        ["pink_tulip"] = "whiteflowers", ["oxeye_daisy"] = "whiteflowers",
        ["cornflower"] = "purpleflowers", ["lily_of_the_valley"] = "whiteflowers",
        ["wither_rose"] = "purpleflowers", ["torchflower"] = "yellowflowers",
        ["pitcher_plant"] = "purpleflowers",
        ["oak_leaves"] = "leaves", ["spruce_leaves"] = "pineleaves",
        ["birch_leaves"] = "leaves", ["jungle_leaves"] = "leaves",
        ["acacia_leaves"] = "leaves", ["dark_oak_leaves"] = "leaves",
        ["azalea_leaves"] = "mapleleaves", ["flowering_azalea_leaves"] = "leaves",
        ["oak_log"] = "wood", ["spruce_log"] = "wood", ["birch_log"] = "birchwood",
        ["jungle_log"] = "wood", ["acacia_log"] = "wood", ["dark_oak_log"] = "woodveneer",
        ["stripped_oak_log"] = "wood", ["stripped_spruce_log"] = "wood",
        ["stripped_birch_log"] = "birchwood", ["stripped_jungle_log"] = "wood",
        ["stripped_acacia_log"] = "wood", ["stripped_dark_oak_log"] = "wood",
        ["oak_wood"] = "wood", ["spruce_wood"] = "wood", ["birch_wood"] = "birchwood",
        ["jungle_wood"] = "wood", ["acacia_wood"] = "wood", ["dark_oak_wood"] = "woodveneer",
        ["oak_planks"] = "woodplank", ["spruce_planks"] = "woodplank",
        ["birch_planks"] = "birchwoodplank", ["jungle_planks"] = "woodplank",
        ["acacia_planks"] = "woodplank", ["dark_oak_planks"] = "woodveneer",
        ["mangrove_planks"] = "woodplank", ["cherry_planks"] = "colorpink",
        ["bamboo_planks"] = "wovenleaves", ["crimson_planks"] = "colordarkred",
        ["warped_planks"] = "woodplank",
        ["white_wool"] = "whitewool", ["orange_wool"] = "colororange",
        ["magenta_wool"] = "colorpurple", ["light_blue_wool"] = "colorlightblue",
        ["yellow_wool"] = "coloryellow", ["lime_wool"] = "colorlime",
        ["pink_wool"] = "colorpink", ["gray_wool"] = "colordarkgray",
        ["light_gray_wool"] = "colorsmoothgray", ["cyan_wool"] = "colorsmoothgray",
        ["purple_wool"] = "colorpurple", ["blue_wool"] = "colorblue",
        ["brown_wool"] = "colorbrown", ["green_wool"] = "colorgreen",
        ["red_wool"] = "colorred", ["black_wool"] = "colorblack",
        ["white_carpet"] = "snowlayer", ["orange_carpet"] = "snowlayer",
        ["magenta_carpet"] = "snowlayer", ["light_blue_carpet"] = "snowlayer",
        ["yellow_carpet"] = "snowlayer", ["lime_carpet"] = "snowlayer",
        ["pink_carpet"] = "snowlayer", ["gray_carpet"] = "snowlayer",
        ["light_gray_carpet"] = "snowlayer", ["cyan_carpet"] = "snowlayer",
        ["purple_carpet"] = "snowlayer", ["blue_carpet"] = "snowlayer",
        ["brown_carpet"] = "snowlayer", ["green_carpet"] = "snowlayer",
        ["red_carpet"] = "snowlayer", ["black_carpet"] = "snowlayer",
        ["white_terracotta"] = "colorcreme", ["orange_terracotta"] = "colororange",
        ["magenta_terracotta"] = "colorpurple", ["light_blue_terracotta"] = "colorlightblue",
        ["yellow_terracotta"] = "coloryellow", ["lime_terracotta"] = "colorlime",
        ["pink_terracotta"] = "colorpink", ["gray_terracotta"] = "colorgray",
        ["light_gray_terracotta"] = "colorsmoothgray",
        ["cyan_terracotta"] = "colorsmoothgray", ["purple_terracotta"] = "colorpurple",
        ["blue_terracotta"] = "colorpurple", ["brown_terracotta"] = "colorbrown",
        ["green_terracotta"] = "colordarkgreen", ["red_terracotta"] = "colorbloodOrange",
        ["black_terracotta"] = "colordarkgray", ["terracotta"] = "colorleather",
        ["white_concrete"] = "colorwhite", ["orange_concrete"] = "colororange",
        ["magenta_concrete"] = "colorpurple", ["light_blue_concrete"] = "colorlightblue",
        ["yellow_concrete"] = "coloryellow", ["lime_concrete"] = "colorlime",
        ["pink_concrete"] = "colorpink", ["gray_concrete"] = "colorgray",
        ["light_gray_concrete"] = "colorsmoothgray", ["cyan_concrete"] = "colorcyan",
        ["purple_concrete"] = "colorpurple", ["blue_concrete"] = "colorblue",
        ["brown_concrete"] = "colorbrown", ["green_concrete"] = "colorgreen",
        ["red_concrete"] = "colorred", ["black_concrete"] = "colorblack",
        ["white_concrete_powder"] = "colorwhite", ["orange_concrete_powder"] = "colororange",
        ["magenta_concrete_powder"] = "colorpurple",
        ["light_blue_concrete_powder"] = "colorlightblue",
        ["yellow_concrete_powder"] = "coloryellow", ["lime_concrete_powder"] = "colorlime",
        ["pink_concrete_powder"] = "colorpink", ["gray_concrete_powder"] = "colorgray",
        ["light_gray_concrete_powder"] = "colorsmoothgray",
        ["cyan_concrete_powder"] = "colorcyan", ["purple_concrete_powder"] = "colorpurple",
        ["blue_concrete_powder"] = "colorblue", ["brown_concrete_powder"] = "colorbrown",
        ["green_concrete_powder"] = "colorgreen", ["red_concrete_powder"] = "colorred",
        ["black_concrete_powder"] = "colorblack",
        ["white_stained_glass"] = "stainedglass", ["orange_stained_glass"] = "stainedglass",
        ["magenta_stained_glass"] = "stainedglass",
        ["light_blue_stained_glass"] = "stainedglass",
        ["yellow_stained_glass"] = "stainedglass", ["lime_stained_glass"] = "stainedglass",
        ["pink_stained_glass"] = "stainedglass", ["gray_stained_glass"] = "stainedglass",
        ["light_gray_stained_glass"] = "stainedglass",
        ["cyan_stained_glass"] = "stainedglass", ["purple_stained_glass"] = "stainedglass",
        ["blue_stained_glass"] = "stainedglass", ["brown_stained_glass"] = "stainedglass",
        ["green_stained_glass"] = "stainedglass", ["red_stained_glass"] = "stainedglass",
        ["black_stained_glass"] = "stainedglass",
        ["white_stained_glass_pane"] = "stainedglass",
        ["orange_stained_glass_pane"] = "stainedglass",
        ["magenta_stained_glass_pane"] = "stainedglass",
        ["light_blue_stained_glass_pane"] = "stainedglass",
        ["yellow_stained_glass_pane"] = "stainedglass",
        ["lime_stained_glass_pane"] = "stainedglass",
        ["pink_stained_glass_pane"] = "stainedglass",
        ["gray_stained_glass_pane"] = "stainedglass",
        ["light_gray_stained_glass_pane"] = "stainedglass",
        ["cyan_stained_glass_pane"] = "stainedglass",
        ["purple_stained_glass_pane"] = "stainedglass",
        ["blue_stained_glass_pane"] = "stainedglass",
        ["brown_stained_glass_pane"] = "stainedglass",
        ["green_stained_glass_pane"] = "stainedglass",
        ["red_stained_glass_pane"] = "stainedglass",
        ["black_stained_glass_pane"] = "stainedglass",
        ["white_glazed_terracotta"] = "terracottatile",
        ["orange_glazed_terracotta"] = "terracottatile",
        ["magenta_glazed_terracotta"] = "terracottatile",
        ["light_blue_glazed_terracotta"] = "terracottatile",
        ["yellow_glazed_terracotta"] = "terracottatile",
        ["lime_glazed_terracotta"] = "terracottatile",
        ["pink_glazed_terracotta"] = "terracottatile",
        ["gray_glazed_terracotta"] = "terracottatile",
        ["light_gray_glazed_terracotta"] = "terracottatile",
        ["cyan_glazed_terracotta"] = "terracottatile",
        ["purple_glazed_terracotta"] = "terracottatile",
        ["blue_glazed_terracotta"] = "terracottatile",
        ["brown_glazed_terracotta"] = "terracottatile",
        ["green_glazed_terracotta"] = "terracottatile",
        ["red_glazed_terracotta"] = "terracottatile",
        ["black_glazed_terracotta"] = "terracottatile",
        ["tnt"] = "colorred", ["sponge"] = "coloryellow", ["wet_sponge"] = "coloryellow",
        ["melon"] = "colorgreen", ["pumpkin"] = "colororange",
        ["carved_pumpkin"] = "colororange", ["jack_o_lantern"] = "colororange",
        ["cactus"] = "cactus", ["bamboo"] = "colorgreen",
        ["chain"] = "steelportcullis", ["lightning_rod"] = "copper",
        ["composter"] = "crate", ["barrel"] = "crate",
        ["loom"] = "woodplank", ["cartography_table"] = "table",
        ["fletching_table"] = "table", ["smithing_table"] = "table",
        ["grindstone"] = "stonebrick", ["stonecutter"] = "stonebrick",
        ["bell"] = "goldblock", ["beehive"] = "sunbox", ["bee_nest"] = "sunbox",
        ["cake"] = "button",
        ["chiseled_polished_blackstone"] = "polishedkomatiite",
        ["lectern"] = "woodplank", ["smoker"] = "stonebrick",
        ["blast_furnace"] = "steelplating", ["respawn_anchor"] = "coal",
        ["lodestone"] = "steelplating", ["crying_obsidian"] = "coal",
        ["blackstone"] = "titanium", ["polished_blackstone"] = "titanium",
        ["polished_blackstone_bricks"] = "titanium", ["gilded_blackstone"] = "coal",
        ["blackstone_stairs"] = "stairs", ["polished_blackstone_stairs"] = "stairs",
        ["polished_blackstone_brick_stairs"] = "stairs",
        ["blackstone_slab"] = "halfblock", ["polished_blackstone_slab"] = "halfblock",
        ["polished_blackstone_brick_slab"] = "halfblock",
        ["blackstone_wall"] = "coal", ["polished_blackstone_wall"] = "titanium",
        ["polished_blackstone_brick_wall"] = "titanium",
        ["deepslate"] = "mossycobblestone", ["cobbled_deepslate"] = "mossycobblestone",
        ["polished_deepslate"] = "mossycobblestone",
        ["deepslate_bricks"] = "mossycobblestone", ["deepslate_tiles"] = "mossycobblestone",
        ["cobbled_deepslate_stairs"] = "stairs", ["polished_deepslate_stairs"] = "stairs",
        ["deepslate_brick_stairs"] = "stairs", ["deepslate_tile_stairs"] = "stairs",
        ["cobbled_deepslate_slab"] = "halfblock",
        ["polished_deepslate_slab"] = "halfblock",
        ["deepslate_brick_slab"] = "halfblock", ["deepslate_tile_slab"] = "halfblock",
        ["cobbled_deepslate_wall"] = "stonebrick",
        ["polished_deepslate_wall"] = "stonewall",
        ["deepslate_brick_wall"] = "mossycobblestone",
        ["deepslate_tile_wall"] = "mossycobblestone",
        ["calcite"] = "polishedmarble", ["dripstone_block"] = "sandstone",
        ["pointed_dripstone"] = "sandstone",
        ["amethyst_block"] = "colorpurple", ["budding_amethyst"] = "colorpurple",
        ["amethyst_cluster"] = "sapphire",
        ["tuff"] = "stonebrick", ["tuff_bricks"] = "stonebrick",
        ["polished_tuff"] = "stonebrick",
        ["tuff_brick_stairs"] = "stairs", ["tuff_brick_slab"] = "halfblock",
        ["tuff_brick_wall"] = "stonebrick",
        ["polished_tuff_stairs"] = "stairs", ["polished_tuff_slab"] = "halfblock",
        ["polished_tuff_wall"] = "stonebrick",
        ["mud"] = "komatiite", ["mud_bricks"] = "bricks",
        ["mud_brick_stairs"] = "stairs", ["mud_brick_slab"] = "halfblock",
        ["mud_brick_wall"] = "bricks", ["packed_mud"] = "dirt",
        ["moss_block"] = "grass", ["moss_carpet"] = "snowlayer",
        ["copper_block"] = "copper", ["exposed_copper"] = "copper",
        ["weathered_copper"] = "copper", ["oxidized_copper"] = "copper",
        ["cut_copper"] = "copper", ["exposed_cut_copper"] = "copper",
        ["weathered_cut_copper"] = "copper", ["oxidized_cut_copper"] = "copper",
        ["cut_copper_stairs"] = "stairs", ["exposed_cut_copper_stairs"] = "stairs",
        ["weathered_cut_copper_stairs"] = "stairs",
        ["oxidized_cut_copper_stairs"] = "stairs",
        ["cut_copper_slab"] = "halfblock", ["exposed_cut_copper_slab"] = "halfblock",
        ["weathered_cut_copper_slab"] = "halfblock",
        ["oxidized_cut_copper_slab"] = "halfblock",
        ["waxed_copper_block"] = "copper", ["waxed_exposed_copper"] = "copper",
        ["waxed_weathered_copper"] = "copper", ["waxed_oxidized_copper"] = "copper",
        ["waxed_cut_copper"] = "copper", ["waxed_exposed_cut_copper"] = "copper",
        ["waxed_weathered_cut_copper"] = "copper",
        ["waxed_oxidized_cut_copper"] = "copper",
        ["raw_copper_block"] = "copper", ["raw_iron_block"] = "iron",
        ["raw_gold_block"] = "goldblock",
        ["mangrove_log"] = "wood", ["mangrove_wood"] = "wood",
        ["stripped_mangrove_log"] = "wood", ["stripped_mangrove_wood"] = "wood",
        ["mangrove_leaves"] = "leaves", ["mangrove_roots"] = "wood",
        ["muddy_mangrove_roots"] = "dirt",
        ["cherry_log"] = "colorpink", ["cherry_wood"] = "colorpink",
        ["stripped_cherry_log"] = "colorpink", ["stripped_cherry_wood"] = "colorpink",
        ["cherry_slab"] = "halfblock", ["cherry_stairs"] = "stairs",
        ["cherry_fence"] = "fence", ["cherry_fence_gate"] = "fence",
        ["cherry_trapdoor"] = "trapdoor", ["cherry_leaves"] = "colorpink",
        ["pale_oak_log"] = "wood", ["pale_oak_wood"] = "wood",
        ["stripped_pale_oak_log"] = "wood", ["stripped_pale_oak_wood"] = "wood",
        ["pale_oak_planks"] = "woodplank", ["pale_oak_slab"] = "halfblock",
        ["pale_oak_stairs"] = "stairs", ["pale_oak_fence"] = "fence",
        ["pale_oak_fence_gate"] = "fence", ["pale_oak_trapdoor"] = "trapdoor",
        ["pale_oak_leaves"] = "leaves",
        ["bamboo_block"] = "coloryellow", ["stripped_bamboo_block"] = "wovenleaves",
        ["bamboo_slab"] = "halfblock", ["bamboo_stairs"] = "stairs",
        ["bamboo_fence"] = "fence", ["bamboo_fence_gate"] = "fence",
        ["bamboo_trapdoor"] = "trapdoor",
        ["bamboo_mosaic"] = "coloryellow", ["bamboo_mosaic_slab"] = "halfblock",
        ["bamboo_mosaic_stairs"] = "stairs",
        ["crimson_stem"] = "colordarkred", ["stripped_crimson_stem"] = "colordarkred",
        ["crimson_hyphae"] = "colordarkred", ["stripped_crimson_hyphae"] = "colordarkred",
        ["crimson_slab"] = "halfblock", ["crimson_stairs"] = "stairs",
        ["crimson_fence"] = "fence", ["crimson_fence_gate"] = "fence",
        ["crimson_trapdoor"] = "trapdoor",
        ["warped_stem"] = "colorcyan", ["stripped_warped_stem"] = "colorcyan",
        ["warped_hyphae"] = "colorcyan", ["stripped_warped_hyphae"] = "colorcyan",
        ["warped_slab"] = "halfblock", ["warped_stairs"] = "stairs",
        ["warped_fence"] = "fence", ["warped_fence_gate"] = "fence",
        ["warped_trapdoor"] = "trapdoor",
        ["warped_nylium"] = "colorcyan", ["crimson_nylium"] = "colordarkred",
        ["crimson_fungus"] = "redmushroom",
        ["warped_wart_block"] = "colorcyan", ["shroomlight"] = "techlamp",
        ["sculk"] = "coal", ["sculk_catalyst"] = "coal",
        ["sculk_shrieker"] = "coal", ["sculk_sensor"] = "bluebox",
        ["sculk_vein"] = "coal", ["reinforced_deepslate"] = "coal",
        ["ochre_froglight"] = "pineleaves", ["verdant_froglight"] = "colorgreen",
        ["pearlescent_froglight"] = "colorpurple",
        ["decorated_pot"] = "bricks", ["suspicious_sand"] = "sand",
        ["suspicious_gravel"] = "cobblestone", ["chiseled_bookshelf"] = "bookcase",
        ["mangrove_fence"] = "fence", ["mangrove_fence_gate"] = "fence",
        ["mangrove_slab"] = "halfblock", ["mangrove_stairs"] = "stairs",
        ["copper_trapdoor"] = "trapdoor", ["exposed_copper_trapdoor"] = "trapdoor",
        ["weathered_copper_trapdoor"] = "trapdoor",
        ["oxidized_copper_trapdoor"] = "trapdoor",
        ["waxed_copper_trapdoor"] = "trapdoor",
        ["waxed_exposed_copper_trapdoor"] = "trapdoor",
        ["waxed_weathered_copper_trapdoor"] = "trapdoor",
        ["waxed_oxidized_copper_trapdoor"] = "trapdoor",
        ["chiseled_copper"] = "copper",
        ["copper_grate"] = "copper", ["copper_bulb"] = "copper",
        ["diamond_block"] = "diamond", ["iron_block"] = "iron",
        ["redstone_block"] = "colorred", ["lapis_block"] = "colordarkblue",
        ["lapis_ore"] = "colordarkblue", ["diamond_ore"] = "diamond",
        ["iron_ore"] = "iron", ["gold_ore"] = "gold", ["coal_ore"] = "coal",
        ["copper_ore"] = "copper", ["redstone_ore"] = "colorred",
        ["deepslate_iron_ore"] = "iron", ["deepslate_gold_ore"] = "gold",
        ["deepslate_diamond_ore"] = "diamond", ["deepslate_coal_ore"] = "coal",
        ["deepslate_copper_ore"] = "copper", ["deepslate_redstone_ore"] = "colorred",
        ["deepslate_lapis_ore"] = "colordarkblue",
        ["deepslate_emerald_ore"] = "uranium",
        ["mossy_cobblestone"] = "mossycobblestone",
        ["mossy_stone_bricks"] = "mossycobblestone",
        ["chiseled_stone_bricks"] = "stonebrick",
        ["smooth_stone"] = "polishedgranite",
        ["polished_andesite"] = "polishedandesite",
        ["polished_diorite"] = "polisheddiorite",
        ["polished_granite"] = "polishedgranite",
        ["snow_block"] = "snow", ["snow"] = "snowlayer",
        ["red_sandstone"] = "sandstone", ["chiseled_sandstone"] = "sandstone",
        ["chiseled_red_sandstone"] = "sandstone", ["cut_sandstone"] = "sandstone",
        ["cut_red_sandstone"] = "sandstone", ["smooth_sandstone"] = "sandstone",
        ["smooth_red_sandstone"] = "sandstone",
        ["red_sand"] = "sand",
        ["piston"] = "steelplating", ["sticky_piston"] = "steelplating",
        ["observer"] = "stonebrick", ["dispenser"] = "stonebrick",
        ["dropper"] = "stonebrick", ["target"] = "colorwhite",
        ["daylight_detector"] = "woodplank",
        ["white_bed"] = null, ["orange_bed"] = null, ["magenta_bed"] = null,
        ["light_blue_bed"] = null, ["yellow_bed"] = null, ["lime_bed"] = null,
        ["pink_bed"] = null, ["gray_bed"] = null, ["light_gray_bed"] = null,
        ["cyan_bed"] = null, ["purple_bed"] = null, ["blue_bed"] = null,
        ["brown_bed"] = null, ["green_bed"] = null, ["red_bed"] = null, ["black_bed"] = null,
        ["brown_mushroom"] = "redmushroom", ["red_mushroom"] = "redmushroom",
        ["brown_mushroom_block"] = "redmushroom", ["red_mushroom_block"] = "redmushroom",
        ["slime_block"] = "colorlime",
        ["sponge"] = "coloryellow",
    };

    public static byte TmBlockId(string name)
    {
        if (TmBlockEnum.TryGetValue(name, out byte id))
            return id;
        string cleaned = name.Replace("_", "").Replace(" ", "");
        if (TmBlockEnum.TryGetValue(cleaned, out id))
            return id;
        return 0;
    }

    public static bool IsSkipBlock(string mcName) => SkipBlocks.Contains(mcName);

    public static byte ResolveMcBlock(string mcName, Dictionary<string, string>? props = null)
    {
        if (SkipBlocks.Contains(mcName))
            return 0;

        if (DoorBlocks.TryGetValue(mcName, out string? doorTarget))
        {
            string half = props?.GetValueOrDefault("half", "lower") ?? "lower";
            if (half == "upper") return 0;
            return TmBlockId(doorTarget);
        }

        if (McToTm.TryGetValue(mcName, out string? target))
        {
            if (target == null) return 0;
            return TmBlockId(target);
        }

        byte bid = TmBlockId(mcName);
        if (bid != 0) return bid;

        return TmBlockId("cobblestone");
    }
}